apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vpn-switcher
  namespace: argocd
  annotations:
    avp.kubernetes.io/path: "k8secrets/vpnswitcher"    
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          vpn-switcher: "installed"
      values:
        revision: '{{metadata.annotations.branch-name}}'          
  template:
    metadata:
      name: '{{name}}-vpn-switcher' 
    spec:
      project: k8s-rpi-apps
      sources:
      - helm:
          releaseName: vpnswitcher
          values: |
            defaultPodOptions:
              securityContext:
                runAsUser: 1000
                runAsGroup: 1000
            persistence:
              config:
                enabled: true
                type: secret
                name: vpnswitcher-config
                mountPath: /etc/vpnswitcher/config.yaml
                subPath: config.yml
            controllers:
              main:
                containers:
                  main:
                    nameOverride: vpnswitcher
                    image:
                      repository: quay.io/vadimzharov/vpnswitcher
                      pullPolicy: IfNotPresent
                      tag: latest
                    ports:
                    - name: http
                      containerPort: 8080
                      protocol: TCP
            service:
              main:
                primary: true              
                enabled: true
                controller: main
                ports:
                  http:
                    port: 8080
            ingress:
              main:
                enabled: true
                ingressClassName: nginx
                hosts:
                  - host: <path:k8secrets/ingresses#vpnswitcherhostname>.<path:k8secrets/ingresses#domainname>
                    paths:
                      - path: /
                        pathType: Prefix
                        service:
                          name: main
                          port: http
            secrets:
              config:
                enabled: true
                stringData:
                  config.yaml: |
                                         <config>
        repoURL: https://bjw-s.github.io/helm-charts
        chart: app-template
        targetRevision: 2.3.0
      destination:
        server: '{{server}}'
        namespace: vpn-switcher
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          