apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vikunja
  namespace: argocd
  annotations:
    avp.kubernetes.io/path: "k8secrets/ingresses"
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          vikunja: "installed"
      values:
        revision: '{{metadata.annotations.branch-name}}'
  template:
    metadata:
      name: '{{name}}-vikunja'
    spec:
      project: k8s-rpi-apps
      sources:
      - helm:
          releaseName: vikunja
          values: |
            frontend:
              # Public API URL that client's browser will reach
              apiUrl: "https://<vikunjaapihostname>.<domainname>/api/v1"
              env:
                - name: "VIKUNJA_HTTP2_PORT"
                  value: "8081"
              ingress:
                enabled: true
                className: ""
                annotations:
                  nginx.ingress.kubernetes.io/ssl-redirect: "true"
                  nginx.ingress.kubernetes.io/force-ssl-redirect: "true"                
                hosts:
                  - host: <vikunjahostname>.<domainname>
                    paths:
                      - path: /
                        pathType: ImplementationSpecific
                tls: []              
            api:
              cache:
                enabled: false
                type: redis
              ingress:
                enabled: true
                className: ""
                annotations:
                  nginx.ingress.kubernetes.io/ssl-redirect: "true"
                  nginx.ingress.kubernetes.io/force-ssl-redirect: "true"                
                hosts:
                  - host: <vikunjaapihostname>.<domainname>
                    paths:
                      - path: /
                        pathType: ImplementationSpecific
                tls: []                   
              extraVolumes:
                - name: sqlite
                  emptyDir: {}
              extraVolumeMounts:
                - name:  sqlite
                  mountPath: /sqlite
        repoURL: https://kolaente.dev/api/packages/vikunja/helm
        chart: vikunja
        targetRevision: 0.2.0
      destination:
        server: '{{server}}' 
        namespace: vikunja
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      