apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vikunja
  namespace: argocd
  annotations:
    avp.kubernetes.io/path: "k8secrets/ingresses"
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          vikunja: "installed"
      values:
        revision: '{{metadata.annotations.branch-name}}'
  template:
    metadata:
      name: '{{name}}-vikunja'
    spec:
      project: k8s-rpi-apps
      sources:
      - helm:
          releaseName: vikunja
          values: |
            image:
              repository: vikunja/api
              pullPolicy: IfNotPresent
              tag: 0.21.0
            service:
              main:
                ports:
                  api:
                    port: 3456
                    primary: true
                  http:
                    port: 8080
                    primary: false
                annotations:
                  service.cilium.io/global: "true"                  
            sidecars:
              frontend:
                image: vikunja/frontend:0.21.0
                env:
                  VIKUNJA_HTTP2_PORT: "8081"                
            api:
              env:
                - name: VIKUNJA_SERVICE_FRONTENDURL
                  value: https://tasks.${EXTERNAL_DOMAIN}
                - name: VIKUNJA_SERVICE_JWT
                  value: <path:k8secrets/vikunja#jwtsecret>
                - name: VIKUNJA_SERVICE_ENABLEREGISTRATION
                  value: "1"
            persistence:
              config:
                enabled: true
                type: emptyDir
                mountPath: /sqlite
            ingress:
              main:
                enabled: true
                className: ""
                annotations:
                  nginx.ingress.kubernetes.io/ssl-redirect: "true"
                  nginx.ingress.kubernetes.io/force-ssl-redirect: "true"                
                hosts:
                  - host: <vikunjahostname>.<domainname>
                    paths:
                      - path: /
                        pathType: ImplementationSpecific
                        service:
                          name: vikunja
                          port: 8080
        repoURL: https://bjw-s.github.io/helm-charts
        chart: app-template
        targetRevision: 1.5.1
      destination:
        server: '{{server}}' 
        namespace: vikunja
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      